# Generated by Django 4.2.1 on 2023-06-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0027_delete_mylibrary'),
        ('users', '0003_remove_profile_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_books', models.ManyToManyField(blank=True, related_name='finished_users', to='store.book')),
                ('reading_books', models.ManyToManyField(blank=True, related_name='reading_users', to='store.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mylibrary', to=settings.AUTH_USER_MODEL)),
                ('watchlist_books', models.ManyToManyField(blank=True, related_name='watchlist_users', to='store.book')),
            ],
        ),
    ]
