# Generated by Django 4.2.1 on 2023-06-24 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_mylibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_mylibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylibrary',
            name='finished_books',
        ),
        migrations.RemoveField(
            model_name='mylibrary',
            name='reading_books',
        ),
        migrations.RemoveField(
            model_name='mylibrary',
            name='watchlist_books',
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='in_library', to='store.book'),
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='status',
            field=models.CharField(choices=[('READING', 'Reading'), ('WATCHLIST', 'Watchlist'), ('FINISHED', 'Finished')], default='READING', max_length=20),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_library', to=settings.AUTH_USER_MODEL),
        ),
    ]
