# Generated by Django 4.2.1 on 2023-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_mylibrary_finished_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='status',
            field=models.IntegerField(choices=[(0, 'Reading'), (1, 'Watchlist'), (2, 'Finished')], default=0),
        ),
    ]
