# Generated by Django 4.2.1 on 2023-06-24 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_mylibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_mylibrary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylibrary',
            name='books',
            field=models.ManyToManyField(to='store.book'),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='status',
            field=models.CharField(choices=[('W', 'Watchlist'), ('R', 'Reading'), ('F', 'Finished')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
