# Generated by Django 4.2.1 on 2023-06-24 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_mylibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_mylibrary_books_alter_mylibrary_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylibrary',
            name='books',
        ),
        migrations.RemoveField(
            model_name='mylibrary',
            name='status',
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='finished_books',
            field=models.ManyToManyField(blank=True, related_name='finished_users', to='store.book'),
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='reading_books',
            field=models.ManyToManyField(blank=True, related_name='reading_users', to='store.book'),
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='watchlist_books',
            field=models.ManyToManyField(blank=True, related_name='watchlist_users', to='store.book'),
        ),
        migrations.AlterField(
            model_name='mylibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mylibrary', to=settings.AUTH_USER_MODEL),
        ),
    ]
