# Generated by Django 4.2.1 on 2023-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='points',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='achievement_images'),
        ),
    ]
