# Generated by Django 4.2.1 on 2023-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_achievement_points_alter_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='users.achievement'),
        ),
    ]
