# Generated by Django 4.2.1 on 2023-07-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
