# Generated by Django 4.2.1 on 2023-07-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_webpage_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage_settings',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
