# Generated by Django 4.2.1 on 2023-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_webpage_settings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage_settings',
            name='display_dob_option',
            field=models.IntegerField(choices=[(0, 'Do not show my date of birth'), (1, 'Show only my day and month'), (2, 'Show my date of birth')], default=0),
        ),
    ]
