# Generated by Django 4.2.1 on 2023-07-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebPage_Settings',
            new_name='WebPageSettings',
        ),
    ]
