# Generated by Django 4.2.1 on 2023-07-25 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_alter_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
