# Generated by Django 4.2.1 on 2023-07-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_blacklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='username',
        ),
    ]
