# Generated by Django 4.2.1 on 2023-07-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_nickname_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='nickname',
        ),
    ]
