# Generated by Django 4.2.1 on 2023-07-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
