# Generated by Django 4.2.1 on 2023-08-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_conversation_messages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
