# Generated by Django 4.2.1 on 2023-08-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_add_reading',
            field=models.BooleanField(default=True),
        ),
    ]
