# Generated by Django 4.2.1 on 2023-08-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_auto_add_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_add_reading',
            field=models.BooleanField(default=False),
        ),
    ]
