# Generated by Django 4.2.1 on 2023-08-07 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_profile_library_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_books', models.ManyToManyField(blank=True, related_name='finished_users', to='store.book')),
                ('reading_books', models.ManyToManyField(blank=True, related_name='reading_users', to='store.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
                ('watchlist_books', models.ManyToManyField(blank=True, related_name='watchlist_users', to='store.book')),
            ],
        ),
        migrations.DeleteModel(
            name='MyLibrary',
        ),
    ]
