# Generated by Django 4.2.1 on 2023-11-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_book_series'),
        ('users', '0043_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='watchlist_books',
        ),
        migrations.AddField(
            model_name='library',
            name='favorites_books',
            field=models.ManyToManyField(blank=True, related_name='favorites_users', to='store.book'),
        ),
        migrations.AddField(
            model_name='library',
            name='liked_books',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='store.book'),
        ),
        migrations.AddField(
            model_name='library',
            name='wish_list_books',
            field=models.ManyToManyField(blank=True, related_name='wishlist_users', to='store.book'),
        ),
    ]
