# Generated by Django 4.2.1 on 2023-11-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about',
        ),
    ]
