# Generated by Django 4.2.1 on 2023-11-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_rename_bio_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagesettings',
            name='about',
        ),
        migrations.RemoveField(
            model_name='webpagesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='webpagesettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='webpagesettings',
            name='status',
        ),
        migrations.RemoveField(
            model_name='webpagesettings',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='webpagesettings',
            name='website',
        ),
    ]
