# Generated by Django 4.2.1 on 2023-11-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_webpagesettings_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagesettings',
            name='display_dob_option',
            field=models.IntegerField(choices=[(0, 'No One'), (1, 'Friends Only'), (2, 'Everyone')], default=1),
        ),
    ]
