# Generated by Django 4.2.1 on 2023-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_webpagesettings_display_dob_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='library_privacy',
        ),
        migrations.AddField(
            model_name='profile',
            name='library_visibility',
            field=models.CharField(choices=[('no_one', 'No One'), ('friends', 'Friends Only'), ('everyone', 'Everyone')], default='friends', max_length=10),
        ),
    ]
