# Generated by Django 4.2.1 on 2023-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_remove_profile_library_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagesettings',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auto_add_reading',
            field=models.BooleanField(default=True),
        ),
    ]
