# Generated by Django 4.2.7 on 2023-11-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_webpagesettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(max_length=6),
        ),
    ]
