# Generated by Django 4.2.7 on 2023-11-17 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0054_temporaryregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryregistration',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_by_author', models.BooleanField(default=True)),
                ('show_book_updates', models.BooleanField(default=True)),
                ('show_author_updates', models.BooleanField(default=True)),
                ('newbooks', models.BooleanField(default=False)),
                ('library_readling_updates', models.BooleanField(default=True)),
                ('library_wishlist_updates', models.BooleanField(default=True)),
                ('library_liked_updates', models.BooleanField(default=True)),
                ('show_review_updates', models.BooleanField(default=True)),
                ('show_comment_updates', models.BooleanField(default=True)),
                ('show_follower_updates', models.BooleanField(default=True)),
                ('show_response_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
