# Generated by Django 4.2.7 on 2023-11-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_webpagesettings_dob_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagesettings',
            name='dob_day',
        ),
        migrations.AlterField(
            model_name='temporaryregistration',
            name='dob_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temporaryregistration',
            name='dob_year',
            field=models.IntegerField(),
        ),
    ]
