# Generated by Django 4.2.7 on 2023-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_remove_webpagesettings_dob_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpagesettings',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
