# Generated by Django 4.2.7 on 2023-11-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_webpagesettings_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpagesettings',
            name='dob_month',
            field=models.IntegerField(),
        ),
    ]
