# Generated by Django 4.2.7 on 2023-11-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_webpagesettings_dob_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagesettings',
            name='dob_month',
        ),
        migrations.RemoveField(
            model_name='webpagesettings',
            name='dob_year',
        ),
    ]
