# Generated by Django 4.2.7 on 2023-11-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_chapter_is_free'),
        ('users', '0066_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, related_name='purchased_by_users', to='store.book'),
        ),
    ]
