# Generated by Django 4.2.1 on 2024-02-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0068_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_reading', models.BooleanField(default=True)),
                ('notify_liked', models.BooleanField(default=True)),
                ('notify_wishlist', models.BooleanField(default=True)),
                ('notify_favorites', models.BooleanField(default=True)),
                ('chapter_notification_threshold', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
