# Generated by Django 4.2.1 on 2024-02-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_authornote_book'),
        ('users', '0069_usersnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='store.book'),
        ),
    ]
