# Generated by Django 4.2.1 on 2024-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_alter_notification_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersnotificationsettings',
            name='chapter_notification_threshold',
            field=models.IntegerField(choices=[(1, '1 Chapter'), (3, '3 Chapters'), (5, '5 Chapters'), (10, '10 Chapters'), (30, '30 Chapters')], default=1),
        ),
    ]
