# Generated by Django 4.2.1 on 2024-02-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_alter_usersnotificationsettings_chapter_notification_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='show_book_updates',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('review_update', 'Review Update'), ('book_update', 'Book Update'), ('author_update', 'Author Update')], max_length=30),
        ),
    ]
