# Generated by Django 4.2.1 on 2024-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_remove_notificationsetting_show_book_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='record_history',
            field=models.BooleanField(default=True),
        ),
    ]
