# Generated by Django 4.2.1 on 2024-03-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_profile_record_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsetting',
            old_name='library_readling_updates',
            new_name='library_reading_updates',
        ),
    ]
